// <auto-generated />
using System;
using InclusaoDiversidadeEmpresas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace InclusaoDiversidadeEmpresas.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251129161050_TabelaRelatorios")]
    partial class TabelaRelatorios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InclusaoDiversidadeEmpresas.Models.Colaborador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("EtniaColaborador")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("GeneroColaborador")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NomeColaborador")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<long>("TemDisabilidade")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("TreinamentoCompleto")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tbl_colaboradores", (string)null);
                });

            modelBuilder.Entity("InclusaoDiversidadeEmpresas.Models.ParticipacaoEmTreinamentoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ColaboradorId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("Completo")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("DataDeConclusao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long>("TreinamentoId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.HasIndex("TreinamentoId");

                    b.HasIndex("ColaboradorId", "TreinamentoId")
                        .IsUnique();

                    b.ToTable("tbl_participacao_treinamento", (string)null);
                });

            modelBuilder.Entity("InclusaoDiversidadeEmpresas.Models.RelatorioDeDiversidadeModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ContagemDeMulheres")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ContagemDePessoasComDesabilidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ContagemDePessoasLgbt")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ContagemDePessoasNegras")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataGerada")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("TotalColaborador")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("tbl_relatorios_diversidade", (string)null);
                });

            modelBuilder.Entity("InclusaoDiversidadeEmpresas.Models.TreinamentoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.ToTable("tbl_treinamentos", (string)null);
                });

            modelBuilder.Entity("InclusaoDiversidadeEmpresas.Models.ParticipacaoEmTreinamentoModel", b =>
                {
                    b.HasOne("InclusaoDiversidadeEmpresas.Models.Colaborador", "Colaborador")
                        .WithMany("Participacao")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InclusaoDiversidadeEmpresas.Models.TreinamentoModel", "Treinamento")
                        .WithMany("Participacao")
                        .HasForeignKey("TreinamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Treinamento");
                });

            modelBuilder.Entity("InclusaoDiversidadeEmpresas.Models.Colaborador", b =>
                {
                    b.Navigation("Participacao");
                });

            modelBuilder.Entity("InclusaoDiversidadeEmpresas.Models.TreinamentoModel", b =>
                {
                    b.Navigation("Participacao");
                });
#pragma warning restore 612, 618
        }
    }
}
